[theme]
# Gruvbox Light Theme
primaryColor = "#b8bb26"  # Gruvbox bright green
backgroundColor = "#fbf1c7"  # Gruvbox bg0
secondaryBackgroundColor = "#f2e5bc"  # Gruvbox bg1
textColor = "#3c3836"  # Gruvbox fg1

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
